export * from './schemas.js';  // IQLSchema, UQLSchema, WhereOpEnum, etc.
export * from './types.js';    // Scalar, Field, Entity, UEM, Where, ReadQuery, Adapter...
export * from './trace.js';    // ProofTraceV2, CostSketch, SlotCandidate...
export * from './iem.js';      // IEM types
export { requireIndexed } from './utils/index-guards.js';